// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNext.BienEtreAuTravail.DAL.Context;

namespace VNext.BienEtreAuTravail.DAL.Migrations
{
    [DbContext(typeof(WorkContext))]
    partial class WorkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Commentaire", b =>
                {
                    b.Property<int>("IdCommentaire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CommentOfEmployee")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCommentaire");

                    b.HasIndex("CommentOfEmployee")
                        .IsUnique();

                    b.ToTable("Commentaire");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Departement", b =>
                {
                    b.Property<int>("IdDepartement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomDepartement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomResponsable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDepartement");

                    b.ToTable("Departement");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Employee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDepartement")
                        .HasColumnType("int");

                    b.Property<bool>("IsDepartmentManager")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pseudo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEmployee");

                    b.HasIndex("IdDepartement")
                        .IsUnique()
                        .HasFilter("[IdDepartement] IS NOT NULL");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.HumeurEmployee", b =>
                {
                    b.Property<int>("IdEmployee")
                        .HasColumnType("int");

                    b.Property<int>("IdHumeur")
                        .HasColumnType("int");

                    b.Property<int?>("HumeurEmpMoodId")
                        .HasColumnType("int");

                    b.HasKey("IdEmployee", "IdHumeur");

                    b.HasIndex("HumeurEmpMoodId");

                    b.ToTable("HumeurEmp");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Mood", b =>
                {
                    b.Property<int>("MoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.HasKey("MoodId");

                    b.ToTable("Moods");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Commentaire", b =>
                {
                    b.HasOne("VNext.BienEtreAuTravail.DAL.Models.Database.Employee", "Employee")
                        .WithOne("Commentaire")
                        .HasForeignKey("VNext.BienEtreAuTravail.DAL.Models.Database.Commentaire", "CommentOfEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.Employee", b =>
                {
                    b.HasOne("VNext.BienEtreAuTravail.DAL.Models.Database.Departement", "Departement")
                        .WithOne("Employee")
                        .HasForeignKey("VNext.BienEtreAuTravail.DAL.Models.Database.Employee", "IdDepartement");
                });

            modelBuilder.Entity("VNext.BienEtreAuTravail.DAL.Models.Database.HumeurEmployee", b =>
                {
                    b.HasOne("VNext.BienEtreAuTravail.DAL.Models.Database.Mood", "HumeurEmp")
                        .WithMany()
                        .HasForeignKey("HumeurEmpMoodId");

                    b.HasOne("VNext.BienEtreAuTravail.DAL.Models.Database.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
